prefix: ./tf2-gpu-yml
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - _tflow_select=2.1.0=gpu
  - absl-py=0.13.0=pyhd3eb1b0_0
  - aiohttp=3.7.4=py39h27cfd23_1
  - astor=0.8.1=py39h06a4308_0
  - astunparse=1.6.3=py_0
  - async-timeout=3.0.1=py39h06a4308_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blinker=1.4=py39h06a4308_0
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py39h27cfd23_1003
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.7.5=h06a4308_1
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2021.5.30=py39h06a4308_0
  - cffi=1.14.6=py39h400218f_0
  - chardet=3.0.4=py39h06a4308_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.1=pyhd3eb1b0_0
  - coverage=5.5=py39h27cfd23_2
  - cryptography=3.4.7=py39hd23ed53_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - cupti=10.1.168=0
  - cycler=0.10.0=py39h06a4308_0
  - cython=0.29.24=py39h295c915_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.1=h2531618_2
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.69.1=h5202010_0
  - google-auth=1.33.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=py_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - idna=3.2=pyhd3eb1b0_0
  - importlib-metadata=3.10.0=py39h06a4308_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - jpeg=9b=h024ee3a_2
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.3.1=py39h2531618_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgomp=9.3.0=h5101ec6_17
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.17.2=h4ff587b_1
  - libtiff=4.2.0=h85742a9_0
  - libuuid=1.0.3=h1bed415_2
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - lz4-c=1.9.3=h295c915_1
  - markdown=3.3.4=py39h06a4308_0
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_random=1.2.2=py39h51133e4_0
  - multidict=5.1.0=py39h27cfd23_2
  - munkres=1.1.4=py_0
  - ncurses=6.2=he6710b0_1
  - oauthlib=3.1.1=pyhd3eb1b0_0
  - olefile=0.46=py_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1l=h7f8727e_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - pcre=8.45=h295c915_0
  - pillow=8.3.1=py39h2c7a002_0
  - pip=21.2.4=py37h06a4308_0
  - protobuf=3.17.2=py39h295c915_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py39h2531618_6
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.6=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-flatbuffers=1.12.0
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - requests=2.26.0=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - setuptools=52.0.0=py39h06a4308_0
  - sip=4.19.13=py39h2531618_0
  - six=1.15.0
  - sqlite=3.36.0=hc218d9a_0
  - tensorboard=2.5.0=py_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.4.1=gpu_py39h8236f22_0
  - tensorflow-base=2.4.1=gpu_py39h29c2da4_0
  - tensorflow-estimator=2.4.1
  - tensorflow-gpu=2.4.1=h30adc30_0
  - termcolor=1.1.0=py39h06a4308_1
  - tk=8.6.10=hbc83047_0
  - tornado=6.1=py39h27cfd23_0
  - typing-extensions=4.7.1=py39h06a4308_0
  - typing_extensions=4.7.1=py39h06a4308_0
  - tzdata=2021a=h5d7bf9c_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.37.0=pyhd3eb1b0_0
  - wrapt=1.12.1=py39he8ac12f_1
  - xz=5.2.5=h7b6447c_0
  - yarl=1.6.3=py39h27cfd23_0
  - zipp=3.5.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - awkward==1.1.1
    - cloudpickle==2.0.0
    - deap==1.3.1
    - dm-tree==0.1.6
    - energyflow==1.3.2
    - filelock==3.3.1
    - gym==0.21.0
    - h5py==2.10.0
    - imageio==2.9.0
    - joblib==1.0.1
    - lz4==3.1.3
    - mplhep>=0.3.28,<0.4.0
    - mplhep-data==0.0.3
    - msgpack==1.0.2
    - networkx==2.6.3
    - nflows==0.14
    - numexpr==2.8.4
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - packaging==21.3
    - pandas==1.5.1
    - pathlib==1.0.1
    - patsy==0.5.3
    - pydot==1.4.2
    - pygad==2.16.1
    - pytz==2021.1
    - pywavelets==1.1.1
    - pyyaml==6.0
    - ray==1.7.0
    - redis==3.5.3
    - scikit-image==0.18.3
    - scikit-learn==0.24.2
    - seaborn==0.12.1
    - sklearn==0.0
    - statsmodels==0.13.5
    - stopit==1.1.2
    - tables==3.6.1
    - tabulate==0.8.9
    - tensorboard-data-server==0.6.1
    - tensorboardx==2.4
    - threadpoolctl==2.2.0
    - tifffile==2021.10.12
    - torch==1.13.0
    - tpot==0.11.7
    - tqdm==4.62.3
    - uhi==0.3.2
    - update-checker==0.18.0
    - uproot==4.0.2
    - wasserstein==1.0.1
    - wurlitzer==3.0.2
    - xarray==0.20.0
    - xgboost==1.4.2

